; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\PATEB11\AppData\Local\Temp\1\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
