
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GS_Fills](
	[OPID] [int] NOT NULL,
	[FillID] [int] NOT NULL,
	[OrderID] [int] NOT NULL,
	[LastShares] [dbo].[ShareAmount] NOT NULL,
	[LastPrice] [dbo].[PriceAmount] NOT NULL,
 CONSTRAINT [PK_GS_Fills] PRIMARY KEY CLUSTERED 
(
	[FillID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


